// houses.js – Array of house objects (explicitly attached to window for global access)
window.houses = [
  {
    id: 1,
    title: "Modern Downtown Apartment",
    location: "Addis Ababa Saris",
    price: "8500-ETB / month",
    description:
      "Beautiful 2-bedroom apartment with city views, modern kitchen, and gym access.",
    ownerName: "Biniam Getachew ",
    ownerPhone: "+1 212-555-1234",
    ownerEmail: "BiniamGetachew@email.com",
    availability: "Available from March 1",
    image: "images/houseImages/home24.jpg",
  },
  {
    id: 2,
    title: "One wide Room for ",
    location: "Addis Ababa Bole",
    price: "32000-ETB / month",
    description:
      "Spacious 2-bedroom house with a large backyard, garage, and close to schools.",
    ownerName: "Siraj Edris",
    ownerPhone: "+1 310-555-5678",
    ownerEmail: "SirajEdris@email.com",
    availability: "Available immediately",
    image: "/images/houseImages/home23.jpg",
  },
  {
    id: 3,
    title: "Luxury House",
    location: "Addis Ababa Bole",
    price: "35000-ETB / month",
    description:
      "Stunning 3-bedroom condo with direct beach access, pool, and 24/7 security.",
    ownerName: "Mokenen",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "mike@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home3.jpg",
  },
  {
    id: 4,
    title: "Room for Every Purpose",
    location: "Addis Ababa Kezanchis",
    price: "5000-ETB / month",
    description: "Stunning  finishing  and clean Views",
    ownerName: "Munir Abdu",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "munirs@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home5.jpg",
  },
  {
    id: 5,
    title: "Luxury House",
    location: "Addis Ababa Mexico",
    price: "8500-ETB / month",
    description: "Stunning 2-bedroom with  pool, and 24/7 security.",
    ownerName: "Marta",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "marta12@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home6.jpg",
  },
  {
    id: 6,
    title: "Luxury Appartment",
    location: "Addis Ababa Bole",
    price: "22500-ETB / month",
    description: "Stunning 2-bedroom  and 24/7 security.",
    ownerName: "Tewdros",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "tedi@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home7.jpg",
  },
  {
    id: 7,
    title: "Modern Downtown Apartment",
    location: "Addis Ababa Gotera",
    price: "6,500-ETB / month",
    description:
      "Beautiful 2-bedroom apartment with city views, modern kitchen, and gym access.",
    ownerName: "Abebe",
    ownerPhone: "+1 212-555-1234",
    ownerEmail: "jAbebe@email.com",
    availability: "Available from March 1",
    image: "/images/houseImages/home8.jpg",
  },
  {
    id: 8,
    title: "Cozy Suburban House",
    location: "Addis Ababa Bole",
    price: "18200-ETB / month",
    description:
      "Spacious 4-bedroom house with a large backyard, garage, and close to schools.",
    ownerName: "Tigist",
    ownerPhone: "+1 310-555-5678",
    ownerEmail: "tig!j@email.com",
    availability: "Available immediately",
    image: "/images/houseImages/home9.jpg",
  },
  {
    id: 9,
    title: "Luxury Beachfront Condo",
    location: "Addis Ababa Shaggar city",
    price: "5,500-ETB / month",
    description: "3-bedroom and 24/7 security.",
    ownerName: "Bulcha Abdi",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "Bulcha@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home10.jpg",
  },
  {
    id: 10,
    title: "Luxury Room",
    location: "Addis Ababa Saris",
    price: "7500-ETB / month",
    description:
      "Stunning 3-bedroom condo with direct beach access, pool, and 24/7 security.",
    ownerName: "Mike",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "miko.man@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home11.jpg",
  },
  {
    id: 11,
    title: "Luxury Condo",
    location: "Addis Ababa Bole",
    price: "40500-ETB / month",
    description:
      "Stunning 3-bedroom condo with direct beach access, pool, and 24/7 security.",
    ownerName: "Abdu",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "Abdu@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home12.jpg",
  },
  {
    id: 12,
    title: "Studio",
    location: "Addis Ababa Around France Embassy",
    price: "13000-ETB / month",
    description: "Clean 1-bedroom with access to pool, and 24/7 security.",
    ownerName: "zakir",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "Zeki@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home13.jpg",
  },
  {
    id: 13,
    title: "Luxury Villa",
    location: "Addis Ababa Bole",
    price: "45000-ETB / month",
    description:
      "Stunning 3-bedroom condo with direct beach access, pool, and 24/7 security.",
    ownerName: "Daniel",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "Danidavis@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home14.jpg",
  },
  {
    id: 14,
    title: "Luxury Villa",
    location: "Addis Ababa ",
    price: "47500-ETB / month",
    description:
      "Beautiful 4-bedroom condo with direct beach access, pool, and 24/7 security.",
    ownerName: "Mike Davis",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "mike.davis@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home16.jpg",
  },
  {
    id: 15,
    title: "Luxury Beachfront Condo",
    location: "Addis Ababa Bole",
    price: "15000-ETB / month",
    description:
      "10-bedroom condo with direct beach access, pool, and 24/7 security.",
    ownerName: "Mike Davis",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "mike.davis@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home17.jpg",
  },
  {
    id: 16,
    title: "Luxury Office",
    location: "Addis Ababa Bole",
    price: "21000-ETB / month",
    description: " 24/7 security.",
    ownerName: "Jemal",
    ownerPhone: "+1 305-555-9012",
    ownerEmail: "jemal@email.com",
    availability: "Available from April 15",
    image: "/images/houseImages/home18.jpg",
  },
  // Add more houses below – just copy the structure and increase the id
];

